[general]
runtime_env="github_actions"

[r2]
bucket_name     = "year-in-data"
web_bucket_name = "year-in-data-web"

[github]
username = "aebel-shajan"

[sources]
# Run only these pipelines (empty = run all)
tags_to_run    = ["strong", "gymgroup", "macos_commands", "macos_screentime"]
# Always skip these pipelines
tags_to_ignore = []
