[r2]
bucket_name = "year-in-data"
public_url  = "http://localhost:9000/year-in-data"

[github]
username = "test-user"

[sources]
fitbit    = true
kindle    = true
github    = true
strong    = true
gymgroup    = false
screentime  = false
zsh_history = false
