[general]
runtime_env="local"

[r2]
bucket_name = "year-in-data"
public_url  = "http://localhost:9000/year-in-data"

[github]
username = "test-user"

[sources]
tags_to_run    = ["fitbit", "kindle", "github", "strong"]
tags_to_ignore = []
