name: Run Data Pipeline and Save to Output Branch

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 1 * *'

jobs:
  run-and-store:
    runs-on: ubuntu-latest
    
    env:
      DRIVE_SHARE_URL: ${{ secrets.DRIVE_SHARE_URL }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run pipeline shell script
        run: |
          chmod +x scripts/run-pipeline.sh
          ./scripts/run-pipeline.sh

