name: Run Data Pipeline and Save to Output Branch

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 1 * *'

jobs:
  run-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd pipeline
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the pipeline
        run: |
          cd pipeline
          python main.py  # Replace with your actual script

      - name: Push output to `data-output` branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan data-output-temp
          git rm -rf .
          cp path/to/output/* .  # Copy output files to root
          git add .
          git commit -m "Update pipeline output"
          git push -f origin data-output-temp:data-output
